In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [115]:
da=pd.read_csv('alpha.csv')
X=da.iloc[:,:-1].values
y=da.iloc[:,-1].values

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [116]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [117]:
#X=da.iloc[:,1:3]

#print(X)

In [118]:
y=da.iloc[:,-1]
print(y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [119]:
###   handling missing data ###

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3]= imputer.transform(X[:, 1:3])

print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [120]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [121]:
###  encoding categorical data     (ONE  HOT  ENCODING)###
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

print(X)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
        before label encoder the data is like this

In [122]:
### encoding dependent variable (LABLE ENCODING)###
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


In [123]:
### SPLITTING THE DATASET INTO TRAINING DATASET ###

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [124]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [125]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [126]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [127]:
print(y_test)

[0 1]


In [128]:
###   FEATURE SCALING ###

from sklearn.preprocessing import normalize

X_train[:,3:]=normalize(X_train[:,3:], axis=0)
X_test[:,3:]=normalize(X_test[:,3:], axis=0)

In [129]:
print(X_test)

[[0.0 1.0 0.0 0.6298019584212192 0.6275252832307678]
 [1.0 0.0 0.0 0.7767557487195038 0.778596184749286]]


In [130]:
print(X_train)

[[0.0 0.0 1.0 0.33698516473042683 0.2800616831718899]
 [0.0 1.0 0.0 0.34760647364743164 0.3434944575655231]
 [1.0 0.0 0.0 0.38236712101217485 0.38777771516107834]
 [0.0 0.0 1.0 0.33022614996506006 0.3285338975670247]
 [0.0 0.0 1.0 0.23463436971201637 0.2585184767740522]
 [1.0 0.0 0.0 0.417127768376918 0.4254783263572943]
 [0.0 1.0 0.0 0.4345080920592896 0.447021532755132]
 [1.0 0.0 0.0 0.3041556644415027 0.31237649276864643]]


In [131]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [132]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578598 -1.078125940841242]
 [0.0 1.0 0.0 -0.014117293757059154 -0.07013167641635358]
 [1.0 0.0 0.0 0.5667085065333234 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224995 -0.30786617274297795]
 [0.0 0.0 1.0 -1.9018011447007994 -1.4204636155515815]
 [1.0 0.0 0.0 1.147534306823705 1.2326533634535495]
 [0.0 1.0 0.0 1.4379472069688957 1.5749910381638887]
 [1.0 0.0 0.0 -0.7401495441200356 -0.5646194287757329]]
